<?php
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
	<span class="spn_titulo_itau">Voc&ecirc; ser&aacute; redirecionado para o Ita&uacute; ap&oacute;s a confirma&ccedil;&atilde;o do pedido, podendo utilizar as formas de pagamento que compoem o Ita&uacute; Shopline:</span><br><br>
    <span class="spn_titulo_itau">Boleto Banc&aacute;rio</span><br>
    <span class="spn_titulo_itau">Pagamento a vista por transfer&ecirc;ncia*</span><br>
    <span class="spn_titulo_itau">Cr&eacute;dito Autom&aacute;tico Ita&uacute;*</span><br>
    <span class="spn_titulo_itau">Cart&atilde;o de Cr&eacute;dito ItauCard*</span><br>
    <br/>
    * somente para correntista Ita&uacute;
			</li>
    </ul>
</fieldset>
